baseURL = "http://caspianacres.ca/"
languageCode = "en-us"
title = "Caspian Acres"
publishDir = "docs"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "We are a small farm focused on generating food for our local community"
  facebook = "https://www.facebook.com/caspianacres/"
  twitter = "https://twitter.com/caspian_acres"
  instagram = "https://www.instagram.com/caspian_acres/"
  youtube = "https://www.youtube.com/channel/UCIY2C9haSCebjXPbNV1AQEA"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/muscovy_and_gang.jpg"
